### ISSUE TITLE
Update intl lib to match latest Flutter/dart version pinned by flutter_localizations (0.20.2)

### ISSUE THREAD

**Issue by hugomc92** [Diversido/flutter_twilio_conversations#54]

**Comment by hugomc92** [comment]
Please up

**Comment by hugomc92** [comment]
Please, I need to update Flutter version which depends on `intl` 0.20.2 but as this lib is depending on `intl` 0.19.0 I can't do it

**Comment by MakSinroja** [comment]
@hugomc92 Here is the temporary solution for this issue

```
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl: ^0.19.0

  # Integrate the Twilio Conversations SDK with your Flutter app using this Twilio Conversations Flutter plugin
  flutter_twilio_conversations: ^2.0.9+19

dependency_overrides:
  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl: ^0.20.2
```
